config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "texts#index"
  resources :texts, only: [:index, :show] do
    resource :reads, only: [:create, :destroy]
  end
  devise_for :users

  resources :movies, only: [:index] do
    resources :watches, only: [:create, :destroy]
  end
  resources :questions, only: [:index, :show]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :watches, dependent: :destroy

  validates :genre, presence: true
  validates :title, presence: true
  validates :url, presence: true

  def watch_by?(user)
    watches.find_by(user_id: user.id).present?
  end
end

app/models/question.rb
class Question < ApplicationRecord
  validates :genre, presence: true
  validates :title, presence: true
  validates :content, presence: true
  validates :answer, presence: true
end

app/models/read.rb
class Read < ApplicationRecord
  belongs_to :user
  belongs_to :text
  validates :user_id, uniqueness: {
    scope: :text_id
  }
end

app/models/read_text.rb
class ReadText < ApplicationRecord
  belongs_to :user
  belongs_to :text
  validates :user_id, uniqueness: {
    scope: :text_id,
    message: "は同じテキストに2回以上読破済みにはできません"
  }
end

app/models/text.rb
class Text < ApplicationRecord
  has_many :reads, dependent: :destroy

  validates :genre, presence: true
  validates :title, presence: true
  validates :content, presence: true

  def read_by?(user)
    reads.find_by(user_id: user.id).present?
  end
end

app/models/text_management.rb
class TextManagement < ApplicationRecord
  belongs_to :user
  belongs_to :text
  validates :user_id, uniqueness: {
    scope: :text_id,
    message: "は同じテキストに2回以上読破済みにはできません"
  }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reads, dependent: :destroy
  has_many :watches, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/watch.rb
class Watch < ApplicationRecord
  belongs_to :user
  belongs_to :movie
  validates :user_id, uniqueness: {
    scope: :movie_id,
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.where(genre: ["basic", "git", "ruby", "rails"])
    @watched_movie_ids = current_user.watches.pluck(:movie_id)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @q = Question.ransack(params[:q])
    @questions = @q.result(distinct: true)
  end

  def show
  end
end

app/controllers/read_texts_controller.rb
class ReadTextsController < ApplicationController
  def create
    @text = Text.find(params[:text_id])
    current_user.read_texts.create!(text_id: @text.id)
  end

  def destroy
    @text = Text.find(params[:text_id])
    current_user.read_texts.find_by(text_id: @text.id).destroy!
  end
end

app/controllers/reads_controller.rb
class ReadsController < ApplicationController
  def create
    @text = Text.find(params[:text_id])
    current_user.reads.create!(text_id: @text.id)
  end

  def destroy
    @text = Text.find(params[:text_id])
    current_user.reads.find_by(text_id: @text.id).destroy!
  end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  before_action :authenticate_user!

  def index
    # ()にマッチするレコードを全て取得する
    @texts = Text.where(genre: ["basic", "git", "html", "ruby", "rails"])
    @read_text_ids = current_user.reads.pluck(:text_id)
  end

  def show
    @text = Text.find(params[:id])
  end
end

app/controllers/watches_controller.rb
class WatchesController < ApplicationController
  def create
    @movie = Movie.find(params[:movie_id])
    current_user.watches.create!(movie_id: @movie.id)
  end

  def destroy
    @movie = Movie.find(params[:movie_id])
    current_user.watches.find_by(movie_id: @movie.id).destroy!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def max_width
    devise_controller? ? 'mw-md' : 'mw-xl'
  end

  def not_logged_in
    "disabled" unless user_signed_in?
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    resource.errors.full_messages.each do |error_message|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    end
    html.html_safe
  end
end

app/helpers/markdown_helper.rb
require 'rouge/plugins/redcarpet'
class HTML < Redcarpet::Render::HTML
  include Rouge::Plugins::Redcarpet
end

module MarkdownHelper
  def markdown(text)
    markdown = Redcarpet::Markdown.new(html_renderer, markdown_extensions)
    markdown.render(text).html_safe
  end

  private

  def html_renderer
    #Redcarpet::Render::HTML
    HTML.new(url_options)
  end

  def markdown_extensions
    {
      autolink: true,
      space_after_headers: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      tables: true,
      hard_wrap: true,
      xhtml: true,
      lax_html_blocks: true,
      strikethrough: true
    }
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, msg| %>
  <div class="alert alert-<%= flash_type %>" role="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm navbar-dark fixed-top" style="background-color: #6699FF;">
  <div class="container">
    <a class="navbar-brand" href="#">やんばるエキスパート</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-center" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <div class="collapse navbar-collapse" id="bs-navi">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Ruby</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "Ruby/Railsテキスト教材", texts_path, class: 'dropdown-item' %>
                <%= link_to "Ruby/Rails動画教材", movies_path, class: "dropdown-item #{ not_logged_in }"%>
                <%= link_to "AWSテキスト教材", "#", class: 'dropdown-item' %>
                <%= link_to "よくある質問集", questions_path, class: 'dropdown-item' %>
                <%= link_to "チャレンジ問題集", "#", class: 'dropdown-item' %>
              </div>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">PHP</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "PHPテキスト教材", "#", class: 'dropdown-item' %>
                <%= link_to "PHP動画教材", "#", class: "dropdown-item #{ not_logged_in }" %>
              </div>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">フロント</a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "HTML&CSS", "#", class: 'dropdown-item' %>
                <%= link_to "JavaScript", "#", class: 'dropdown-item' %>
                <%= link_to "TypeScript", "#", class: 'dropdown-item' %>
                <%= link_to "Angular", "#", class: 'dropdown-item' %>
                <%= link_to "Vue", "#", class: 'dropdown-item' %>
              </div>
            </li>

            <li class="nav-item dropdown">
              <% if  %>
                <% user_signed_in? %>
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">勉強会</a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <%= link_to "全ての勉強会", "#", class: 'dropdown-item' %>
                    <%= link_to "プログラミング勉強会", "#", class: 'dropdown-item' %>
                  </div>
                <% else %>
                  <%= link_to "勉強会",  "#", class: 'nav-link disabled' %>
              <% end %>
            </li>

            <li class="nav-item">
                <%= link_to "マネタイズ講座",  "#", class: "nav-link #{ not_logged_in }" %>
            </li>

            <li class="nav-item">
                <%= link_to "LINE", "#", class: 'nav-link' %>
            </li>

            <% if user_signed_in? %>
              <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">マイページ</a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%= link_to "進捗管理", "#", class: 'dropdown-item' %>
                  <%= link_to "アカウント編集", edit_user_registration_path, class: 'dropdown-item' %>
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
                </div>
              </li>
            <% else %>
              <li class="navbar-nav ml-auto">
                <%= link_to "ログイン", new_user_session_path, class: 'nav-link' %>
                <%= link_to "新規登録", new_user_registration_path, class: 'nav-link' %>
              </li>  
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>チーム開発 やんばるCODE教材クローン</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>    
    <header>
      <%= render "layouts/header" %>
      <%= render "layouts/flash" %>
    </header>
    <main>
      <%# max_width メソッドは application_helper.rb に記載 %>
      <div class="base-container <%= max_width %>">
        <%= yield %>
      </div>
    </main>
    <footer>
    </footer>
  </body>
</html>

app/views/movies/_unwatch.html.erb
<%= link_to "視聴済みにする", movie_watches_path(movie), method: :post, class: "btn btn-secondary btn-block", remote: true %>

app/views/movies/_watch.html.erb
<%= link_to "視聴済みを解除", movie_watches_path(movie), method: :delete, class: "btn btn-primary btn-block", remote: true %>

app/views/movies/index.html.erb
<div class="contents-title text-center">
  <h1>Ruby/Rails 動画教材</h1>
</div>
<div class="container-fluid">
  <div class="row">
    <% @movies.each do |movie| %>
      <div class="col-12 col-md-6 col-lg-4">
        <div class="card border-dark mb-3">
          <div class="card-header p-0">
            <div class="embed-responsive embed-responsive-16by9">
              <iframe width="560" height="315" src=<%= movie.url %> frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="allowfullscreen"></iframe>
            </div>
          </div>
          <div class="card-body text-dark movie-body">
            <p class="card-text movie-title">
            <p id="movie-<%= movie.id %>">
              <% if @watched_movie_ids.include?(movie.id) %>
                <%= render "watch", movie: movie %>
              <% else %>
                <%= render "unwatch", movie: movie %>
              <% end %>
            </p>
              <%= movie.title %>
            </p>
          </div>
        </div>
      </div>
    <% end %> 
  </div>
</div>

app/views/questions/index.html.erb
<div class="base-container mw-lg">
  <section id="contents">
  <h1 class="text-center mb-3">よくある質問集</h1>
    <div class="base-container mw-lg">
      <form class="js-filter-form :checkbox">
        <label><input class="checkbox" type="checkbox" name="genre" value="ruby" checked> ruby</label>
        <label><input class="checkbox" type="checkbox" name="genre" value="rails" checked> rails</label>
      </form>
      <%= search_form_for @q do |f| %>
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <div class="form-control input-group-text"><%= f.label :title_cont, "タイトル" %></div>
        </div>
        <%= f.search_field :title_cont, class:"form-control" %>
      </div>
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <div class="form-control input-group-text"><%= f.label :content_cont, "キーワード" %></div>
        </div>
        <%= f.search_field :content_cont,class: "form-control" %>
      </div>
      <%= f.submit:class=>"btn btn-primary btn-block" %>
      <% end %>
    <div>
  <body>
<div class="table-container mt-3">
  <table id="list" class="table table-striped">
    <thead class="text-white base-bf-color">
      <tr class="bg-primary">
        <th class="text-nowrap">ジャンル</th>
        <th class="w-100">タイトル</th>
      </tr>
    </thead>
    <tbody>
      <% @questions.each do |question| %>
        <tr>
          <td class="text-nowrap align-middle question-title"><%= question.genre %></td>
          <td class="break-word"><%= question.title %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
    </section>
</div>
</div>
<script>
$(".js-filter-form :checkbox").on("click", function(){
  var checked = [];
  $(".js-filter-form :checked").each(function(){
    // チェックボックスにチェックした値を配列に追加
    checked.push($(this).val());
    });
    // 全てのtrを取得
    $('#list tbody tr').each(function(){
      var txt = $(this).find("td:eq(0)").html();
      // rubyとrailsにチェックが入ると表示
      if(txt.match(checked[0]) || (checked[1])){
        $(this).show();
      }else{
        $(this).hide();
      }
    });
});
</script>
</body>

app/views/questions/show.html.erb
<h1>Questions#show</h1>
<p>Find me in app/views/questions/show.html.erb</p>

app/views/read_texts/create.js.erb
document.getElementById('text-<%= @text.id %>').innerHTML = '<%= j render("texts/read_text", text: @text) %>'

app/views/read_texts/destroy.js.erb
document.getElementById('text-<%= @text.id %>').innerHTML = '<%= j render("texts/unread_text", text: @text) %>'

app/views/reads/create.js.erb
document.getElementById('text-<%= @text.id %>').innerHTML = '<%= j render("texts/read", text: @text) %>'

app/views/reads/destroy.js.erb
document.getElementById('text-<%= @text.id %>').innerHTML = '<%= j render("texts/unread", text: @text) %>'

app/views/texts/_read.html.erb
<%= link_to "読破済みを解除", text_reads_path(text), method: :delete, class: "btn btn-primary btn-block", remote: true %>

app/views/texts/_read_text.html.erb
<%# 読破済み %>
<%= link_to "読破済みを解除", text_read_texts_path(text), method: :delete, remote: true, class: "btn btn-primary btn-block" %>

app/views/texts/_text.html.erb
<div class="col-12 col-md-6 col-lg-4">
  <div class="card border-dark mb-10">
    <%= link_to text_path(text.id), target: ":_blank" do%>
      <img class="card-img-top" src="https://d5izmuz0mcjzz.cloudfront.net/texts/no_image.jpg" alt="カード画像">
    <% end %>
    <div class="card-body">
      <div id="text-<%= text.id %>">
        <% if @read_text_ids.include?(text.id) %>
          <%= render "read", text: text %>
        <% else %>
          <%= render "unread", text: text %>
        <% end %>
      </div>
      <p class="card-title"><%= text.title %></p>
      <p class="card-text">【<%= text.genre %>】</p>
    </div>
  </div>
</div>

app/views/texts/_unread.html.erb
<%= link_to "読破済みにする", text_reads_path(text), method: :post, class: "btn btn-secondary btn-block", remote: true %>

app/views/texts/_unread_text.html.erb
<%# 未読 %>
<%= link_to "読破済みにする", text_read_texts_path(text), method: :post, remote: true, class: "btn btn-secondary btn-block" %>

app/views/texts/index.html.erb
<div class="texts-wrapper">
  <div class="contents-title text-center">
    <h1>Ruby/Rails テキスト教材</h1>
  </div>
  <div class="row"> 
    <%= render @texts %>
  </div>
</div>

app/views/texts/show.html.erb
<div class="base-container mw-md">
  <section id="text-contents">
    <h2><%= @text.title %></h2>
    <div class="markdown" ><%= markdown(@text.content) %></div>
    <div id="text-<%= @text.id %>">
      <% if @text.read_by?(current_user) %>
        <%= render "read", text: @text %>
      <% else %>
        <%= render "unread", text: @text %>
      <% end %>
    </div>
  </section>
</div>

app/views/watches/create.js.erb
document.getElementById('movie-<%= @movie.id %>').innerHTML = '<%= j render("movies/watch", movie: @movie) %>'

app/views/watches/destroy.js.erb
document.getElementById('movie-<%= @movie.id %>').innerHTML = '<%= j render("movies/unwatch", movie: @movie) %>'